### ISSUE TITLE
"local variable 'result' referenced before assignment" bug preventing cloze additions

### ISSUE THREAD

**Issue by masonc15** [RisingOrange/basic2cloze#2]
# Bug report

## Describe the bug

For the most part, this addon has been working amazingly well but I have been running into this one bug preventing me from adding Clozes into cards.  When I have an existing card that I want to change into a Cloze, I highlight a part of it and enter Ctrl + Shift + C like I would normally do.   As soon as I enter that shortcut, I get the following error: 

```
Anki 2.1.35 (84dcaa86) Python 3.8.0 Qt 5.14.2 PyQt 5.14.2
Platform: Windows 10
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2021-11-18 21:08:50

Caught exception:
Traceback (most recent call last):
  File "aqt\webview.py", line 493, in handler
  File "aqt\editor.py", line 483, in <lambda>
  File "<C:\Program Files\Anki\decorator.pyc:decorator-gen-72>", line 2, in _onCloze
  File "anki\hooks.py", line 638, in decorator_wrapper
  File "anki\hooks.py", line 635, in repl
  File "C:\Users\darks\AppData\Roaming\Anki2\addons21\800723229\basic2cloze.py", line 121, in _onClozeNew
    return result
UnboundLocalError: local variable 'result' referenced before assignment
```

Any help would be appreciated since this is preventing me from turning several cards into Clozes.  Thank you!

**Comment by RisingOrange** [comment]
Sorry that it took me so long to look into this. I just uploaded an update to the add-on that should fix the error. Please let me know if it works for you!
